version: 2
jobs:
  build:
    docker:
      - image: python:latest
    parallelism: 80
    resource_class: xlarge
    steps:
      - run: 
          name: Run Job 
          no_output_timeout: 24h
          command: sleep 5
workflows:
    version: 2
    build:
        jobs:
            - build
